name: nhentai
description: nhentai client
publish_to: 'none'
version: 0.0.9+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_styled_toast: ^2.1.3
  intl: ^0.17.0
  event: ^2.0.5
  waterfall_flow: ^3.0.1
  photo_view: ^0.14.0
  clipboard: ^0.1.3
  hidden_drawer_menu: ^3.0.1
  url_launcher: ^6.1.10
  filesystem_picker: ^3.1.0
  date_format: ^2.0.4
  another_xlider: ^1.1.2
  modal_bottom_sheet: ^2.0.0
  app_links: ^3.4.1
  flutter_inappwebview: ^5.7.2+3
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/
